version: "3.4"
services:
  aaiisentiment:
    build:
      context: "."
      network: lan
    container_name: aaiisentiment
    domainname: example.tld
    hostname: aaiisentiment
    image: simfre/aaiisentiment
    networks:
      lan:
        ipv4_address: 10.0.0.5
        ipv6_address: 2001:db8::5
        aliases:
          - aaiisentiment
    restart: unless-stopped
networks:
  lan:
    external: true
